### ISSUE TITLE
how to use power module

### ISSUE THREAD

**Issue by CatMow** [makinteract/vscode-microbit-micropython#5]
trying to use power module to shut down/deep sleep the micro:bit? when using power.off or power.deep_sleep it doesn't recognise it
![image](https://github.com/makinteract/vscode-microbit-micropython/assets/84914492/67a8e420-5627-4af8-9b04-4d5a34cd8321)
however everything else works, like display and speaker.
how do I fix this?

also can you provide detail on how to use uart? maybe make a video on how to move a motor or something like that

thank you!

**Comment by makinteract** [comment]
Thanks. I think I know where is the issue.... it is a missing import in the stubs. We'll fix it in the next week or so, and then release it as an update. In the meantime, if you do not want to see the error, you can open the `__init__.py` file inside the miro:bit folder, and add the line `import power` at the top of the file. That should give you the IntelliSense you look for. 

Regarding your other comments for help with uart, please look at the examples in [the official documentation](https://microbit-micropython.readthedocs.io/en/v2-docs/uart.html).

**Comment by CatMow** [comment]
ok tysm!
at the moment its this:
import accelerometer
import audio
import compass
import display
import helper
import i2c
import microphone
import neopixel
import radio
import speaker
import speech
import spi
import uart

can I please find out what neopixel, radio, speech is?


also does the touch logo on V2 work, and how do I check for button input? 
btw how do I use speaker? i can use speaker.on() but it wont play anything

**Comment by CatMow** [comment]
![image](https://github.com/makinteract/vscode-microbit-micropython/assets/84914492/2eac5b61-aa1d-4703-b315-6376a73d33c2)
those 4 dont have a file btw, just saying! @makinteract

**Comment by makinteract** [comment]
Hi,
we have updated the imports in the Basic Stubs so now the issue should be solved (version 0.1.26 of the extension), and you should have IntelliSense for power (as requested in your first post).

I am going ahead and marking this issue as **solved**. For other problems, feel free to open up separate issues.

![Screenshot 2023-07-23 at 8 42 59 PM](https://github.com/makinteract/vscode-microbit-micropython/assets/9442196/2b6de658-c5e7-42a8-a3f6-e2bc6bdbd870)
