### ISSUE TITLE
Unable to import pyb module

### ISSUE THREAD

**Issue by adow** [makinteract/vscode-microbit-micropython#6]
I successfully followed the Getting Started guide and was able to run the hello-world program. However, when I tried to use the pyb library (https://docs.micropython.org/en/latest/library/pyb.html#module-pyb), it prompted that this library couldn't be imported.

I noticed that there are not any files related to pyb in the microbit folder.

How can I fix this problem?

Thank you!

**Comment by makinteract** [comment]
The extension is designed to work only with the `BBC micro:bit` board. The `pyboard` is not a supported board.  If however you have a micro:bit and are simply confused about which library to use, the builtin API for the micro:bit is documented here: https://microbit-micropython.readthedocs.io/en/latest.

So, for instance, if you want to use the `delay` function, you would import it from the utime library, as explained here: https://microbit-micropython.readthedocs.io/en/latest/utime.html?highlight=delay#utime.utime.sleep_ms

Just keep in mind that the microbit folder does not contain library code. These libraries are already pre-installed in your micro:bit. What the microbit folder contains are code snippets that activate the IntelliSense in your editor (e.g., for code completion and highlighting). 

Hope it helps!~

PS: I am going to close this issue as it seems to be simply a misunderstanding about what boards are compatible with the extension
