### ISSUE TITLE
Can not use audio.SoundEffect

### ISSUE THREAD

**Issue by cbergmann** [makinteract/vscode-microbit-micropython#7]
Hi,
I want to use a [custom sound effect](https://microbit-micropython.readthedocs.io/en/v2-docs/audio.html#sound-effects-v2).
My demo code is the following:

```
from microbit import *
import audio

while True:
    effect = audio.SoundEffect()
    audio.play(effect,wait=True)
        
    sleep(100)
```

When I flash this to my micro:bit I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
AttributeError: 'module' object has no attribute 'SoundEffect'
```

Can you tell me what I am missing?

**Comment by makinteract** [comment]
The interpreter is telling you that the SoundEffect attribute of audio does not exist on your micro:bit (you might see the text completion on the editor, but the library on your hardware does not have the attribute). Are you using a micro:bit V2?

**Comment by cbergmann** [comment]
yes, I am using a Micro:Bit V2. Is there a way to tell if maybe the installed MicroPython is outdated.

**Comment by makinteract** [comment]
Possible. [This](https://microbit.org/get-started/user-guide/firmware/#micro:bit-v2) is the latest firmware. You could try to install it manually (just a drag-and-drop) and upload your code. If it works, we would know it is the firmware. The extension uses the [uflash](https://github.com/ntoll/uflash) to upload the firmware, and it seems there has not been any update in a couple of years.

**Comment by cbergmann** [comment]
Hi, I think the direction is correct. If I use the [Online Editor for python](https://python.microbit.org/v/3/reference) my code works. It seems that the used version of micropython does not work with the plugin.

**Comment by cbergmann** [comment]
Hi, I looked into the code and found that after flashing the environment for the first time only the python files are [uploaded ](https://github.com/makinteract/vscode-microbit-micropython/blob/1617dab7f69a7c01df8b7d8f21e0ea5d1f016532/src/main.js#L117).
So the following workaround worked for me:
1. Use the [Online Editor](https://python.microbit.org/) to flash any sketch to the micro:bit
2. Thereafter you can use this vsCode plugin to flash custom sketches. Just make sure to never use the "Flash MicroPython environment on the micro:bit" function.

**Comment by makinteract** [comment]
Thank you. I think this settles it and it must be because of an older firmware. The solution you suggested might work for the time being (so I will mark this issue as resolved), but I will probably have to find a better way to handle this. As I mentioned before, the extension uses `uflash` to upload the firmware, which means it would be better to update this dependency rather than an ad-hoc hack. I will look into it, but in the meantime, if you need to use the `SoundEffect` feature, your solution is probably the best.

Thank you!

**Comment by makinteract** [comment]
With version 0.1.30 the firmware uploaded the micro:bit should be the latest one and it should include the functionalities you requested. Hope it helps

**Comment by cbergmann** [comment]
thanks for the update. I will try this out next time I work on my microbit.
