### ISSUE TITLE
Log/Serial functionality

### ISSUE THREAD

**Issue by kashi618** [makinteract/vscode-microbit-micropython#8]
Is there any function to store data from the MicroBit as a CSV file? Such as [Data Logging](https://microbit-micropython.readthedocs.io/en/v2-docs/log.html)

**Comment by makinteract** [comment]
If you have a micro:bit v2 and you have flashed on it the latest firmware, then you should be able to use the native [Data Logging](https://microbit-micropython.readthedocs.io/en/v2-docs/log.html) functionalities (the one for which you posted the link). IntelliSense might not be there, but the code will work. For a similar case, please refer to this [past issue](https://github.com/makinteract/vscode-microbit-micropython/issues/7).

**Comment by makinteract** [comment]
With version 0.1.30 the firmware uploaded to the micro:bit is the latest version, so including the Log functionality. Hope it helps.
